### ISSUE TITLE
Basic S3 copy example does not work out-of-the-box

### ISSUE THREAD

**Issue by abailly** [qmuli/qmuli#3]
I tried running the `simple-s3-copy` example out of a pristine build of qmuli but it does not seem to work: The files (`lambda.zip` and `index.js`) are correctly uploaded to a newly created S3 Bucket but:

1. incoming/outgoing buckets are not created
2. there is no registered lambda function

What am I doing wrong?

**Comment by abailly** [comment]
Example `apigw-lambda-dynamodb` works fine but of course it cannot execute lambda because I compiled it on Mac OS X...

**Comment by ababkin** [comment]
cool, see the instructions on how to build the ec2 box for building lambdas in the README, it shouldn’t take too long

and please let me know.
I hope that soon we won’t need to be spinning up the EC2 boxes to build qmuli

**Comment by abailly** [comment]
That' what I will try to do :)

**Comment by ababkin** [comment]
Great! looking forward to it

**Comment by ababkin** [comment]
Just released the fixes (#4) necessary for the `simple-s3-copy` example
